---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
