---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: |
          python ./tools/checks.py
        language: system
        types: [python]
        pass_filenames: false
