---
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: |
          python3 ./tools/checks.py black
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: |
          python3 ./tools/checks.py flake8
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: |
          python3 ./tools/checks.py mypy
        language: system
        types: [python]
        pass_filenames: false
