---
name: Code Testing

"on":
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 5" # At 07 AM on Friday

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Performs quick checks before the expensive test runs
  check_and_coverage-test:
    if: contains(github.event.pull_request.title, '[skip ci]') == false
    name: "Check and Coverage Test"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        # with:
        # python-version: '3.13' # The version of Python is per default detected from .python-version file

      - name: Install dependencies
        shell: bash
        run: "python ./tools/create_venv.py"

      - name: Perform code checks
        shell: bash
        run: "python ./tools/checks.py"

      - name: Perform Unit and Coverage tests
        shell: bash
        run: "python ./tools/tests.py --e2e"

      - name: Build and check package
        shell: bash
        run: "python ./tools/build.py"

  platform_testing:
    if: contains(github.event.pull_request.title, '[skip ci]') == false
    needs: check_and_coverage-test
    strategy:
      matrix:
        py:
          - "3.10"
          - "3.11"
          - "3.12"
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"

    name: "Python: ${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install dependencies
        shell: bash
        run: "python ./tools/create_venv.py"

      - name: Perform Unit tests
        shell: bash
        run: "python ./tools/tests.py --e2e --no-cov"

  platform_testing_special_linux:
    if: contains(github.event.pull_request.title, '[skip ci]') == false
    needs: check_and_coverage-test
    name: "Special Linux testing"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        shell: bash
        run: "python ./tools/create_venv.py"

      - name: Set up mounted USB stick
        shell: bash
        run: "sudo ./tools/create_fat_volume.sh"

      - name: Perform dfplayer-card-manager tests
        shell: bash
        run: "./tests/test_linux.sh"

  platform_testing_special_windows:
    if: contains(github.event.pull_request.title, '[skip ci]') == false
    needs: check_and_coverage-test
    name: "Special Windows testing"
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        shell: bash
        run: "python ./tools/create_venv.py"

      - name: Set up mounted USB stick
        shell: cmd
        run: ".\\tools\\create_fat_volume.bat"

      - name: Perform dfplayer-card-manager tests
        shell: cmd
        run: ".\\tests\\test_windows.bat"
