---
name: Code Security Scans

"on":
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 5" # At 07 AM on Friday

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

jobs:
  check_and_coverage-test:
    if: contains(github.event.pull_request.title, '[skip ci]') == false
    name: "Run security scans"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install guarddog

      # Scan the project for security vulnerabilities
      - name: Run guarddog
        shell: bash
        run: "python -m guarddog pypi scan ."

      # Scan the dependencies for security vulnerabilities
      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1
        with:
          inputs: ./requirements/constraints.txt ./requirements/base.txt
